irmp.c
IRMP_SUPPORT_GRUNDIG_NOKIA_IR60_PROTOCOL
IRMP_SUPPORT_SIEMENS_OR_RUWIDO_PROTOCOL
IRMP_SUPPORT_MANCHESTER
IRMP_SUPPORT_SERIAL
IRMP_KEY_REPETITION_LEN
MIN_TOLERANCE_00
MAX_TOLERANCE_00
MIN_TOLERANCE_02
MAX_TOLERANCE_02
MIN_TOLERANCE_03
MAX_TOLERANCE_03
MIN_TOLERANCE_05
MAX_TOLERANCE_05
MIN_TOLERANCE_10
MAX_TOLERANCE_10
MIN_TOLERANCE_15
MAX_TOLERANCE_15
MIN_TOLERANCE_20
MAX_TOLERANCE_20
MIN_TOLERANCE_30
MAX_TOLERANCE_30
MIN_TOLERANCE_40
MAX_TOLERANCE_40
MIN_TOLERANCE_50
MAX_TOLERANCE_50
MIN_TOLERANCE_60
MAX_TOLERANCE_60
MIN_TOLERANCE_70
MAX_TOLERANCE_70
SIRCS_START_BIT_PULSE_LEN_MIN
SIRCS_START_BIT_PULSE_LEN_MAX
SIRCS_START_BIT_PAUSE_LEN_MIN
SIRCS_START_BIT_PAUSE_LEN_MAX
SIRCS_1_PULSE_LEN_MIN
SIRCS_1_PULSE_LEN_MAX
SIRCS_0_PULSE_LEN_MIN
SIRCS_0_PULSE_LEN_MAX
SIRCS_PAUSE_LEN_MIN
SIRCS_PAUSE_LEN_MAX
NEC_START_BIT_PULSE_LEN_MIN
NEC_START_BIT_PULSE_LEN_MAX
NEC_START_BIT_PAUSE_LEN_MIN
NEC_START_BIT_PAUSE_LEN_MAX
NEC_REPEAT_START_BIT_PAUSE_LEN_MIN
NEC_REPEAT_START_BIT_PAUSE_LEN_MAX
NEC_PULSE_LEN_MIN
NEC_PULSE_LEN_MAX
NEC_1_PAUSE_LEN_MIN
NEC_1_PAUSE_LEN_MAX
NEC_0_PAUSE_LEN_MIN
NEC_0_PAUSE_LEN_MAX
NEC_FRAME_REPEAT_PAUSE_LEN_MAX
SAMSUNG_START_BIT_PULSE_LEN_MIN
SAMSUNG_START_BIT_PULSE_LEN_MAX
SAMSUNG_START_BIT_PAUSE_LEN_MIN
SAMSUNG_START_BIT_PAUSE_LEN_MAX
SAMSUNG_PULSE_LEN_MIN
SAMSUNG_PULSE_LEN_MAX
SAMSUNG_1_PAUSE_LEN_MIN
SAMSUNG_1_PAUSE_LEN_MAX
SAMSUNG_0_PAUSE_LEN_MIN
SAMSUNG_0_PAUSE_LEN_MAX
SAMSUNGAH_START_BIT_PULSE_LEN_MIN
SAMSUNGAH_START_BIT_PULSE_LEN_MAX
SAMSUNGAH_START_BIT_PAUSE_LEN_MIN
SAMSUNGAH_START_BIT_PAUSE_LEN_MAX
SAMSUNGAH_PULSE_LEN_MIN
SAMSUNGAH_PULSE_LEN_MAX
SAMSUNGAH_1_PAUSE_LEN_MIN
SAMSUNGAH_1_PAUSE_LEN_MAX
SAMSUNGAH_0_PAUSE_LEN_MIN
SAMSUNGAH_0_PAUSE_LEN_MAX
MATSUSHITA_START_BIT_PULSE_LEN_MIN
MATSUSHITA_START_BIT_PULSE_LEN_MAX
MATSUSHITA_START_BIT_PAUSE_LEN_MIN
MATSUSHITA_START_BIT_PAUSE_LEN_MAX
MATSUSHITA_PULSE_LEN_MIN
MATSUSHITA_PULSE_LEN_MAX
MATSUSHITA_1_PAUSE_LEN_MIN
MATSUSHITA_1_PAUSE_LEN_MAX
MATSUSHITA_0_PAUSE_LEN_MIN
MATSUSHITA_0_PAUSE_LEN_MAX
KASEIKYO_START_BIT_PULSE_LEN_MIN
KASEIKYO_START_BIT_PULSE_LEN_MAX
KASEIKYO_START_BIT_PAUSE_LEN_MIN
KASEIKYO_START_BIT_PAUSE_LEN_MAX
KASEIKYO_PULSE_LEN_MIN
KASEIKYO_PULSE_LEN_MAX
KASEIKYO_1_PAUSE_LEN_MIN
KASEIKYO_1_PAUSE_LEN_MAX
KASEIKYO_0_PAUSE_LEN_MIN
KASEIKYO_0_PAUSE_LEN_MAX
MITSU_HEAVY_START_BIT_PULSE_LEN_MIN
MITSU_HEAVY_START_BIT_PULSE_LEN_MAX
MITSU_HEAVY_START_BIT_PAUSE_LEN_MIN
MITSU_HEAVY_START_BIT_PAUSE_LEN_MAX
MITSU_HEAVY_PULSE_LEN_MIN
MITSU_HEAVY_PULSE_LEN_MAX
MITSU_HEAVY_1_PAUSE_LEN_MIN
MITSU_HEAVY_1_PAUSE_LEN_MAX
MITSU_HEAVY_0_PAUSE_LEN_MIN
MITSU_HEAVY_0_PAUSE_LEN_MAX
VINCENT_START_BIT_PULSE_LEN_MIN
VINCENT_START_BIT_PULSE_LEN_MAX
VINCENT_START_BIT_PAUSE_LEN_MIN
VINCENT_START_BIT_PAUSE_LEN_MAX
VINCENT_PULSE_LEN_MIN
VINCENT_PULSE_LEN_MAX
VINCENT_1_PAUSE_LEN_MIN
VINCENT_1_PAUSE_LEN_MAX
VINCENT_0_PAUSE_LEN_MIN
VINCENT_0_PAUSE_LEN_MAX
PANASONIC_START_BIT_PULSE_LEN_MIN
PANASONIC_START_BIT_PULSE_LEN_MAX
PANASONIC_START_BIT_PAUSE_LEN_MIN
PANASONIC_START_BIT_PAUSE_LEN_MAX
PANASONIC_PULSE_LEN_MIN
PANASONIC_PULSE_LEN_MAX
PANASONIC_1_PAUSE_LEN_MIN
PANASONIC_1_PAUSE_LEN_MAX
PANASONIC_0_PAUSE_LEN_MIN
PANASONIC_0_PAUSE_LEN_MAX
RECS80_START_BIT_PULSE_LEN_MIN
RECS80_START_BIT_PULSE_LEN_MAX
RECS80_START_BIT_PAUSE_LEN_MIN
RECS80_START_BIT_PAUSE_LEN_MAX
RECS80_PULSE_LEN_MIN
RECS80_PULSE_LEN_MAX
RECS80_1_PAUSE_LEN_MIN
RECS80_1_PAUSE_LEN_MAX
RECS80_0_PAUSE_LEN_MIN
RECS80_0_PAUSE_LEN_MAX
RC5_START_BIT_LEN_MIN
RC5_START_BIT_LEN_MAX
RC5_BIT_LEN_MIN
RC5_BIT_LEN_MAX
RCII_START_BIT_PULSE_LEN_MIN
RCII_START_BIT_PULSE_LEN_MAX
RCII_START_BIT_PAUSE_LEN_MIN
RCII_START_BIT_PAUSE_LEN_MAX
RCII_START_BIT2_PULSE_LEN_MIN
RCII_START_BIT2_PULSE_LEN_MAX
RCII_BIT_LEN_MIN
RCII_BIT_LEN
RCII_BIT_LEN_MAX
S100_START_BIT_LEN_MIN
S100_START_BIT_LEN_MAX
S100_BIT_LEN_MIN
S100_BIT_LEN_MAX
DENON_PULSE_LEN_MIN
DENON_PULSE_LEN_MAX
DENON_1_PAUSE_LEN_MIN
DENON_1_PAUSE_LEN_MAX
DENON_0_PAUSE_LEN_MIN
DENON_0_PAUSE_LEN_MAX
DENON_AUTO_REPETITION_PAUSE_LEN
THOMSON_PULSE_LEN_MIN
THOMSON_PULSE_LEN_MAX
THOMSON_1_PAUSE_LEN_MIN
THOMSON_1_PAUSE_LEN_MAX
THOMSON_0_PAUSE_LEN_MIN
THOMSON_0_PAUSE_LEN_MAX
RC6_START_BIT_PULSE_LEN_MIN
RC6_START_BIT_PULSE_LEN_MAX
RC6_START_BIT_PAUSE_LEN_MIN
RC6_START_BIT_PAUSE_LEN_MAX
RC6_TOGGLE_BIT_LEN_MIN
RC6_TOGGLE_BIT_LEN_MAX
RC6_BIT_PULSE_LEN_MIN
RC6_BIT_PULSE_LEN_MAX
RC6_BIT_PAUSE_LEN_MIN
RC6_BIT_PAUSE_LEN_MAX
RECS80EXT_START_BIT_PULSE_LEN_MIN
RECS80EXT_START_BIT_PULSE_LEN_MAX
RECS80EXT_START_BIT_PAUSE_LEN_MIN
RECS80EXT_START_BIT_PAUSE_LEN_MAX
RECS80EXT_PULSE_LEN_MIN
RECS80EXT_PULSE_LEN_MAX
RECS80EXT_1_PAUSE_LEN_MIN
RECS80EXT_1_PAUSE_LEN_MAX
RECS80EXT_0_PAUSE_LEN_MIN
RECS80EXT_0_PAUSE_LEN_MAX
NUBERT_START_BIT_PULSE_LEN_MIN
NUBERT_START_BIT_PULSE_LEN_MAX
NUBERT_START_BIT_PAUSE_LEN_MIN
NUBERT_START_BIT_PAUSE_LEN_MAX
NUBERT_1_PULSE_LEN_MIN
NUBERT_1_PULSE_LEN_MAX
NUBERT_1_PAUSE_LEN_MIN
NUBERT_1_PAUSE_LEN_MAX
NUBERT_0_PULSE_LEN_MIN
NUBERT_0_PULSE_LEN_MAX
NUBERT_0_PAUSE_LEN_MIN
NUBERT_0_PAUSE_LEN_MAX
FAN_START_BIT_PULSE_LEN_MIN
FAN_START_BIT_PULSE_LEN_MAX
FAN_START_BIT_PAUSE_LEN_MIN
FAN_START_BIT_PAUSE_LEN_MAX
FAN_1_PULSE_LEN_MIN
FAN_1_PULSE_LEN_MAX
FAN_1_PAUSE_LEN_MIN
FAN_1_PAUSE_LEN_MAX
FAN_0_PULSE_LEN_MIN
FAN_0_PULSE_LEN_MAX
FAN_0_PAUSE_LEN_MIN
FAN_0_PAUSE_LEN_MAX
SPEAKER_START_BIT_PULSE_LEN_MIN
SPEAKER_START_BIT_PULSE_LEN_MAX
SPEAKER_START_BIT_PAUSE_LEN_MIN
SPEAKER_START_BIT_PAUSE_LEN_MAX
SPEAKER_1_PULSE_LEN_MIN
SPEAKER_1_PULSE_LEN_MAX
SPEAKER_1_PAUSE_LEN_MIN
SPEAKER_1_PAUSE_LEN_MAX
SPEAKER_0_PULSE_LEN_MIN
SPEAKER_0_PULSE_LEN_MAX
SPEAKER_0_PAUSE_LEN_MIN
SPEAKER_0_PAUSE_LEN_MAX
BANG_OLUFSEN_START_BIT1_PULSE_LEN_MIN
BANG_OLUFSEN_START_BIT1_PULSE_LEN_MAX
BANG_OLUFSEN_START_BIT1_PAUSE_LEN_MIN
BANG_OLUFSEN_START_BIT1_PAUSE_LEN_MAX
BANG_OLUFSEN_START_BIT2_PULSE_LEN_MIN
BANG_OLUFSEN_START_BIT2_PULSE_LEN_MAX
BANG_OLUFSEN_START_BIT2_PAUSE_LEN_MIN
BANG_OLUFSEN_START_BIT2_PAUSE_LEN_MAX
BANG_OLUFSEN_START_BIT3_PULSE_LEN_MIN
BANG_OLUFSEN_START_BIT3_PULSE_LEN_MAX
BANG_OLUFSEN_START_BIT3_PAUSE_LEN_MIN
BANG_OLUFSEN_START_BIT3_PAUSE_LEN_MAX
BANG_OLUFSEN_START_BIT4_PULSE_LEN_MIN
BANG_OLUFSEN_START_BIT4_PULSE_LEN_MAX
BANG_OLUFSEN_START_BIT4_PAUSE_LEN_MIN
BANG_OLUFSEN_START_BIT4_PAUSE_LEN_MAX
BANG_OLUFSEN_PULSE_LEN_MIN
BANG_OLUFSEN_PULSE_LEN_MAX
BANG_OLUFSEN_1_PAUSE_LEN_MIN
BANG_OLUFSEN_1_PAUSE_LEN_MAX
BANG_OLUFSEN_0_PAUSE_LEN_MIN
BANG_OLUFSEN_0_PAUSE_LEN_MAX
BANG_OLUFSEN_R_PAUSE_LEN_MIN
BANG_OLUFSEN_R_PAUSE_LEN_MAX
BANG_OLUFSEN_TRAILER_BIT_PAUSE_LEN_MIN
BANG_OLUFSEN_TRAILER_BIT_PAUSE_LEN_MAX
IR60_TIMEOUT_LEN
GRUNDIG_NOKIA_IR60_START_BIT_LEN_MIN
GRUNDIG_NOKIA_IR60_START_BIT_LEN_MAX
GRUNDIG_NOKIA_IR60_BIT_LEN_MIN
GRUNDIG_NOKIA_IR60_BIT_LEN_MAX
GRUNDIG_NOKIA_IR60_PRE_PAUSE_LEN_MIN
GRUNDIG_NOKIA_IR60_PRE_PAUSE_LEN_MAX
SIEMENS_OR_RUWIDO_START_BIT_PULSE_LEN_MIN
SIEMENS_OR_RUWIDO_START_BIT_PULSE_LEN_MAX
SIEMENS_OR_RUWIDO_START_BIT_PAUSE_LEN_MIN
SIEMENS_OR_RUWIDO_START_BIT_PAUSE_LEN_MAX
SIEMENS_OR_RUWIDO_BIT_PULSE_LEN_MIN
SIEMENS_OR_RUWIDO_BIT_PULSE_LEN_MAX
SIEMENS_OR_RUWIDO_BIT_PAUSE_LEN_MIN
SIEMENS_OR_RUWIDO_BIT_PAUSE_LEN_MAX
FDC_START_BIT_PULSE_LEN_MIN
FDC_START_BIT_PULSE_LEN_MAX
FDC_START_BIT_PAUSE_LEN_MIN
FDC_START_BIT_PAUSE_LEN_MAX
FDC_PULSE_LEN_MIN
FDC_PULSE_LEN_MAX
FDC_1_PAUSE_LEN_MIN
FDC_1_PAUSE_LEN_MAX
FDC_0_PAUSE_LEN_MIN
FDC_0_PAUSE_LEN_MAX
RCCAR_START_BIT_PULSE_LEN_MIN
RCCAR_START_BIT_PULSE_LEN_MAX
RCCAR_START_BIT_PAUSE_LEN_MIN
RCCAR_START_BIT_PAUSE_LEN_MAX
RCCAR_PULSE_LEN_MIN
RCCAR_PULSE_LEN_MAX
RCCAR_1_PAUSE_LEN_MIN
RCCAR_1_PAUSE_LEN_MAX
RCCAR_0_PAUSE_LEN_MIN
RCCAR_0_PAUSE_LEN_MAX
JVC_START_BIT_PULSE_LEN_MIN
JVC_START_BIT_PULSE_LEN_MAX
JVC_REPEAT_START_BIT_PAUSE_LEN_MIN
JVC_REPEAT_START_BIT_PAUSE_LEN_MAX
JVC_PULSE_LEN_MIN
JVC_PULSE_LEN_MAX
JVC_1_PAUSE_LEN_MIN
JVC_1_PAUSE_LEN_MAX
JVC_0_PAUSE_LEN_MIN
JVC_0_PAUSE_LEN_MAX
JVC_FRAME_REPEAT_PAUSE_LEN_MAX
NIKON_START_BIT_PULSE_LEN_MIN
NIKON_START_BIT_PULSE_LEN_MAX
NIKON_START_BIT_PAUSE_LEN_MIN
NIKON_START_BIT_PAUSE_LEN_MAX
NIKON_REPEAT_START_BIT_PAUSE_LEN_MIN
NIKON_REPEAT_START_BIT_PAUSE_LEN_MAX
NIKON_PULSE_LEN_MIN
NIKON_PULSE_LEN_MAX
NIKON_1_PAUSE_LEN_MIN
NIKON_1_PAUSE_LEN_MAX
NIKON_0_PAUSE_LEN_MIN
NIKON_0_PAUSE_LEN_MAX
NIKON_FRAME_REPEAT_PAUSE_LEN_MAX
KATHREIN_START_BIT_PULSE_LEN_MIN
KATHREIN_START_BIT_PULSE_LEN_MAX
KATHREIN_START_BIT_PAUSE_LEN_MIN
KATHREIN_START_BIT_PAUSE_LEN_MAX
KATHREIN_1_PULSE_LEN_MIN
KATHREIN_1_PULSE_LEN_MAX
KATHREIN_1_PAUSE_LEN_MIN
KATHREIN_1_PAUSE_LEN_MAX
KATHREIN_0_PULSE_LEN_MIN
KATHREIN_0_PULSE_LEN_MAX
KATHREIN_0_PAUSE_LEN_MIN
KATHREIN_0_PAUSE_LEN_MAX
KATHREIN_SYNC_BIT_PAUSE_LEN_MIN
KATHREIN_SYNC_BIT_PAUSE_LEN_MAX
NETBOX_START_BIT_PULSE_LEN_MIN
NETBOX_START_BIT_PULSE_LEN_MAX
NETBOX_START_BIT_PAUSE_LEN_MIN
NETBOX_START_BIT_PAUSE_LEN_MAX
NETBOX_PULSE_LEN
NETBOX_PAUSE_LEN
NETBOX_PULSE_REST_LEN
NETBOX_PAUSE_REST_LEN
LEGO_START_BIT_PULSE_LEN_MIN
LEGO_START_BIT_PULSE_LEN_MAX
LEGO_START_BIT_PAUSE_LEN_MIN
LEGO_START_BIT_PAUSE_LEN_MAX
LEGO_PULSE_LEN_MIN
LEGO_PULSE_LEN_MAX
LEGO_1_PAUSE_LEN_MIN
LEGO_1_PAUSE_LEN_MAX
LEGO_0_PAUSE_LEN_MIN
LEGO_0_PAUSE_LEN_MAX
IRMP16_START_BIT_PULSE_LEN_MIN
IRMP16_START_BIT_PULSE_LEN_MAX
IRMP16_START_BIT_PAUSE_LEN_MIN
IRMP16_START_BIT_PAUSE_LEN_MAX
IRMP16_PULSE_LEN_MIN
IRMP16_PULSE_LEN_MAX
IRMP16_1_PAUSE_LEN_MIN
IRMP16_1_PAUSE_LEN_MAX
IRMP16_0_PAUSE_LEN_MIN
IRMP16_0_PAUSE_LEN_MAX
GREE_START_BIT_PULSE_LEN_MIN
GREE_START_BIT_PULSE_LEN_MAX
GREE_START_BIT_PAUSE_LEN_MIN
GREE_START_BIT_PAUSE_LEN_MAX
GREE_PULSE_LEN_MIN
GREE_PULSE_LEN_MAX
GREE_1_PAUSE_LEN_MIN
GREE_1_PAUSE_LEN_MAX
GREE_0_PAUSE_LEN_MIN
GREE_0_PAUSE_LEN_MAX
BOSE_START_BIT_PULSE_LEN_MIN
BOSE_START_BIT_PULSE_LEN_MAX
BOSE_START_BIT_PAUSE_LEN_MIN
BOSE_START_BIT_PAUSE_LEN_MAX
BOSE_PULSE_LEN_MIN
BOSE_PULSE_LEN_MAX
BOSE_1_PAUSE_LEN_MIN
BOSE_1_PAUSE_LEN_MAX
BOSE_0_PAUSE_LEN_MIN
BOSE_0_PAUSE_LEN_MAX
BOSE_FRAME_REPEAT_PAUSE_LEN_MAX
A1TVBOX_START_BIT_PULSE_LEN_MIN
A1TVBOX_START_BIT_PULSE_LEN_MAX
A1TVBOX_START_BIT_PAUSE_LEN_MIN
A1TVBOX_START_BIT_PAUSE_LEN_MAX
A1TVBOX_BIT_PULSE_LEN_MIN
A1TVBOX_BIT_PULSE_LEN_MAX
A1TVBOX_BIT_PAUSE_LEN_MIN
A1TVBOX_BIT_PAUSE_LEN_MAX
MERLIN_START_BIT_PULSE_LEN_MIN
MERLIN_START_BIT_PULSE_LEN_MAX
MERLIN_START_BIT_PAUSE_LEN_MIN
MERLIN_START_BIT_PAUSE_LEN_MAX
MERLIN_BIT_PULSE_LEN_MIN
MERLIN_BIT_PULSE_LEN_MAX
MERLIN_BIT_PAUSE_LEN_MIN
MERLIN_BIT_PAUSE_LEN_MAX
ORTEK_START_BIT_PULSE_LEN_MIN
ORTEK_START_BIT_PULSE_LEN_MAX
ORTEK_START_BIT_PAUSE_LEN_MIN
ORTEK_START_BIT_PAUSE_LEN_MAX
ORTEK_BIT_PULSE_LEN_MIN
ORTEK_BIT_PULSE_LEN_MAX
ORTEK_BIT_PAUSE_LEN_MIN
ORTEK_BIT_PAUSE_LEN_MAX
TELEFUNKEN_START_BIT_PULSE_LEN_MIN
TELEFUNKEN_START_BIT_PULSE_LEN_MAX
TELEFUNKEN_START_BIT_PAUSE_LEN_MIN
TELEFUNKEN_START_BIT_PAUSE_LEN_MAX
TELEFUNKEN_PULSE_LEN_MIN
TELEFUNKEN_PULSE_LEN_MAX
TELEFUNKEN_1_PAUSE_LEN_MIN
TELEFUNKEN_1_PAUSE_LEN_MAX
TELEFUNKEN_0_PAUSE_LEN_MIN
TELEFUNKEN_0_PAUSE_LEN_MAX
ROOMBA_START_BIT_PULSE_LEN_MIN
ROOMBA_START_BIT_PULSE_LEN_MAX
ROOMBA_START_BIT_PAUSE_LEN_MIN
ROOMBA_START_BIT_PAUSE_LEN_MAX
ROOMBA_1_PAUSE_LEN_EXACT
ROOMBA_1_PULSE_LEN_MIN
ROOMBA_1_PULSE_LEN_MAX
ROOMBA_1_PAUSE_LEN_MIN
ROOMBA_1_PAUSE_LEN_MAX
ROOMBA_0_PAUSE_LEN
ROOMBA_0_PULSE_LEN_MIN
ROOMBA_0_PULSE_LEN_MAX
ROOMBA_0_PAUSE_LEN_MIN
ROOMBA_0_PAUSE_LEN_MAX
RCMM32_START_BIT_PULSE_LEN_MIN
RCMM32_START_BIT_PULSE_LEN_MAX
RCMM32_START_BIT_PAUSE_LEN_MIN
RCMM32_START_BIT_PAUSE_LEN_MAX
RCMM32_BIT_PULSE_LEN_MIN
RCMM32_BIT_PULSE_LEN_MAX
RCMM32_BIT_00_PAUSE_LEN_MIN
RCMM32_BIT_00_PAUSE_LEN_MAX
RCMM32_BIT_01_PAUSE_LEN_MIN
RCMM32_BIT_01_PAUSE_LEN_MAX
RCMM32_BIT_10_PAUSE_LEN_MIN
RCMM32_BIT_10_PAUSE_LEN_MAX
RCMM32_BIT_11_PAUSE_LEN_MIN
RCMM32_BIT_11_PAUSE_LEN_MAX
PENTAX_START_BIT_PULSE_LEN_MIN
PENTAX_START_BIT_PULSE_LEN_MAX
PENTAX_START_BIT_PAUSE_LEN_MIN
PENTAX_START_BIT_PAUSE_LEN_MAX
PENTAX_1_PAUSE_LEN_EXACT
PENTAX_PULSE_LEN_MIN
PENTAX_PULSE_LEN_MAX
PENTAX_1_PAUSE_LEN_MIN
PENTAX_1_PAUSE_LEN_MAX
PENTAX_0_PAUSE_LEN
PENTAX_PULSE_LEN_MIN
PENTAX_PULSE_LEN_MAX
PENTAX_0_PAUSE_LEN_MIN
PENTAX_0_PAUSE_LEN_MAX
ACP24_START_BIT_PULSE_LEN_MIN
ACP24_START_BIT_PULSE_LEN_MAX
ACP24_START_BIT_PAUSE_LEN_MIN
ACP24_START_BIT_PAUSE_LEN_MAX
ACP24_PULSE_LEN_MIN
ACP24_PULSE_LEN_MAX
ACP24_1_PAUSE_LEN_MIN
ACP24_1_PAUSE_LEN_MAX
ACP24_0_PAUSE_LEN_MIN
ACP24_0_PAUSE_LEN_MAX
METZ_START_BIT_PULSE_LEN_MIN
METZ_START_BIT_PULSE_LEN_MAX
METZ_START_BIT_PAUSE_LEN_MIN
METZ_START_BIT_PAUSE_LEN_MAX
METZ_PULSE_LEN_MIN
METZ_PULSE_LEN_MAX
METZ_1_PAUSE_LEN_MIN
METZ_1_PAUSE_LEN_MAX
METZ_0_PAUSE_LEN_MIN
METZ_0_PAUSE_LEN_MAX
METZ_FRAME_REPEAT_PAUSE_LEN_MAX
RADIO1_START_BIT_PULSE_LEN_MIN
RADIO1_START_BIT_PULSE_LEN_MAX
RADIO1_START_BIT_PAUSE_LEN_MIN
RADIO1_START_BIT_PAUSE_LEN_MAX
RADIO1_1_PAUSE_LEN_EXACT
RADIO1_1_PULSE_LEN_MIN
RADIO1_1_PULSE_LEN_MAX
RADIO1_1_PAUSE_LEN_MIN
RADIO1_1_PAUSE_LEN_MAX
RADIO1_0_PAUSE_LEN
RADIO1_0_PULSE_LEN_MIN
RADIO1_0_PULSE_LEN_MAX
RADIO1_0_PAUSE_LEN_MIN
RADIO1_0_PAUSE_LEN_MAX
AUTO_FRAME_REPETITION_LEN
ANALYZE_PUTCHAR
ANALYZE_ONLY_NORMAL_PUTCHAR
ANALYZE_PRINTF
ANALYZE_ONLY_NORMAL_PRINTF
ANALYZE_NEWLINE
PARITY_CHECK_OK
PARITY_CHECK_FAILED
irmp_log
input
STATE_LEFT_SHIFT
STATE_RIGHT_SHIFT
STATE_LEFT_CTRL
STATE_LEFT_ALT
STATE_RIGHT_ALT
KEY_ESCAPE
KEY_MENUE
KEY_BACK
KEY_FORWARD
KEY_ADDRESS
KEY_WINDOW
KEY_1ST_PAGE
KEY_STOP
KEY_MAIL
KEY_FAVORITES
KEY_NEW_PAGE
KEY_SETUP
KEY_FONT
KEY_PRINT
KEY_ON_OFF
KEY_INSERT
KEY_DELETE
KEY_LEFT
KEY_HOME
KEY_END
KEY_UP
KEY_DOWN
KEY_PAGE_UP
KEY_PAGE_DOWN
KEY_RIGHT
KEY_MOUSE_1
KEY_MOUSE_2
int silent
int time_counter
int verbose
const char* const irmp_protocol_names [IRMP_N_PROTOCOLS + 1] PROGMEM
uint_fast8_t irmp_bit
IRMP_PARAMETER irmp_param
volatile uint_fast8_t irmp_ir_detected
volatile uint_fast8_t irmp_protocol
volatile uint_fast16_t irmp_address
volatile uint_fast16_t irmp_command
volatile uint_fast16_t irmp_id
volatile uint_fast8_t irmp_flags
uint_fast8_t IRMP_PIN
uint_fast8_t radio
uint_fast16_t irmp_tmp_address
uint_fast16_t irmp_tmp_command
uint32_t s_curSample
uint32_t s_startBitSample
int analyze
int list
IRMP_DATA irmp_data
int expected_protocol
int expected_address
int expected_command
int do_check_expected_values
uint_fast8_t irmp_get_data(IRMP_DATA *irmp_data_p)
References IRMP_PACKED_STRUCT::address, ANALYZE_PRINTF, IRMP_PACKED_STRUCT::command, FALSE, IRMP_PACKED_STRUCT::flags, IRMP_APPLE_PROTOCOL, IRMP_BOSE_PROTOCOL, IRMP_IR60_PROTOCOL, IRMP_KATHREIN_PROTOCOL, IRMP_LEGO_PROTOCOL, IRMP_MERLIN_PROTOCOL, IRMP_METZ_PROTOCOL, IRMP_NEC_PROTOCOL, IRMP_NETBOX_PROTOCOL, IRMP_ONKYO_PROTOCOL, IRMP_RC5_PROTOCOL, IRMP_RCCAR_PROTOCOL, IRMP_RUWIDO_PROTOCOL, IRMP_S100_PROTOCOL, IRMP_SAMSUNG48_PROTOCOL, IRMP_SAMSUNG_PROTOCOL, IRMP_SIEMENS_PROTOCOL, IRMP_UNKNOWN_PROTOCOL, IRMP_VINCENT_PROTOCOL, IRMP_PACKED_STRUCT::protocol, TRUE.
Referenced by irmp_get_result_data, irmp_reset_state.
static void irmp_store_bit(uint_fast8_t value)
uint_fast8_t irmp_ISR(void)
References A1TVBOX_START_BIT_PAUSE_LEN_MAX, A1TVBOX_START_BIT_PAUSE_LEN_MIN, A1TVBOX_START_BIT_PULSE_LEN_MAX, A1TVBOX_START_BIT_PULSE_LEN_MIN, ACP24_START_BIT_PAUSE_LEN_MAX, ACP24_START_BIT_PAUSE_LEN_MIN, ACP24_START_BIT_PULSE_LEN_MAX, ACP24_START_BIT_PULSE_LEN_MIN, ANALYZE_NEWLINE, ANALYZE_ONLY_NORMAL_PRINTF, ANALYZE_ONLY_NORMAL_PUTCHAR, ANALYZE_PRINTF, ANALYZE_PUTCHAR, AUTO_FRAME_REPETITION_LEN, BANG_OLUFSEN_R_PAUSE_LEN_MAX, BANG_OLUFSEN_R_PAUSE_LEN_MIN, BANG_OLUFSEN_START_BIT1_PAUSE_LEN_MAX, BANG_OLUFSEN_START_BIT1_PAUSE_LEN_MIN, BANG_OLUFSEN_START_BIT1_PULSE_LEN_MAX, BANG_OLUFSEN_START_BIT1_PULSE_LEN_MIN, BANG_OLUFSEN_START_BIT2_PAUSE_LEN_MAX, BANG_OLUFSEN_START_BIT2_PAUSE_LEN_MIN, BANG_OLUFSEN_START_BIT2_PULSE_LEN_MAX, BANG_OLUFSEN_START_BIT2_PULSE_LEN_MIN, BANG_OLUFSEN_START_BIT3_PAUSE_LEN_MAX, BANG_OLUFSEN_START_BIT3_PAUSE_LEN_MIN, BANG_OLUFSEN_START_BIT3_PULSE_LEN_MAX, BANG_OLUFSEN_START_BIT3_PULSE_LEN_MIN, BANG_OLUFSEN_START_BIT4_PAUSE_LEN_MAX, BANG_OLUFSEN_START_BIT4_PAUSE_LEN_MIN, BANG_OLUFSEN_START_BIT4_PULSE_LEN_MAX, BANG_OLUFSEN_START_BIT4_PULSE_LEN_MIN, BOSE_START_BIT_PAUSE_LEN_MAX, BOSE_START_BIT_PAUSE_LEN_MIN, BOSE_START_BIT_PULSE_LEN_MAX, BOSE_START_BIT_PULSE_LEN_MIN, DENON_0_PAUSE_LEN_MAX, DENON_0_PAUSE_LEN_MIN, DENON_1_PAUSE_LEN_MAX, DENON_1_PAUSE_LEN_MIN, DENON_AUTO_REPETITION_PAUSE_LEN, DENON_PULSE_LEN_MAX, DENON_PULSE_LEN_MIN, FALSE, FAN_0_PAUSE_LEN_MIN, FAN_1_PAUSE_LEN_MIN, FAN_1_PULSE_LEN_MIN, FAN_COMPLETE_DATA_LEN, FAN_START_BIT_PAUSE_LEN_MAX, FAN_START_BIT_PAUSE_LEN_MIN, FAN_START_BIT_PULSE_LEN_MAX, FAN_START_BIT_PULSE_LEN_MIN, FDC_0_PAUSE_LEN_MAX, FDC_0_PAUSE_LEN_MIN, FDC_1_PAUSE_LEN_MAX, FDC_1_PAUSE_LEN_MIN, FDC_PULSE_LEN_MAX, FDC_PULSE_LEN_MIN, FDC_START_BIT_PAUSE_LEN_MAX, FDC_START_BIT_PAUSE_LEN_MIN, FDC_START_BIT_PULSE_LEN_MAX, FDC_START_BIT_PULSE_LEN_MIN, GREE_START_BIT_PAUSE_LEN_MAX, GREE_START_BIT_PAUSE_LEN_MIN, GREE_START_BIT_PULSE_LEN_MAX, GREE_START_BIT_PULSE_LEN_MIN, GRUNDIG_COMPLETE_DATA_LEN, GRUNDIG_NOKIA_IR60_PRE_PAUSE_LEN_MAX, GRUNDIG_NOKIA_IR60_PRE_PAUSE_LEN_MIN, GRUNDIG_NOKIA_IR60_START_BIT_LEN_MAX, GRUNDIG_NOKIA_IR60_START_BIT_LEN_MIN, input, IR60_ADDRESS_LEN, IR60_ADDRESS_OFFSET, IR60_COMMAND_LEN, IR60_COMMAND_OFFSET, IR60_COMPLETE_DATA_LEN, IR60_TIMEOUT_LEN, IRMP16_START_BIT_PAUSE_LEN_MAX, IRMP16_START_BIT_PAUSE_LEN_MIN, IRMP16_START_BIT_PULSE_LEN_MAX, IRMP16_START_BIT_PULSE_LEN_MIN, IRMP_BANG_OLUFSEN_PROTOCOL, IRMP_DENON_PROTOCOL, IRMP_FAN_PROTOCOL, IRMP_FDC_PROTOCOL, IRMP_FLAG_REPETITION, IRMP_GRUNDIG_PROTOCOL, IRMP_IR60_PROTOCOL, IRMP_JVC_PROTOCOL, IRMP_KASEIKYO_PROTOCOL, IRMP_KATHREIN_PROTOCOL, IRMP_KEY_REPETITION_LEN, IRMP_LGAIR_PROTOCOL, irmp_log, IRMP_MATSUSHITA_PROTOCOL, IRMP_MERLIN_PROTOCOL, IRMP_MITSU_HEAVY_PROTOCOL, IRMP_NEC42_PROTOCOL, IRMP_NEC_PROTOCOL, IRMP_NETBOX_PROTOCOL, IRMP_NOKIA_PROTOCOL, IRMP_NUBERT_PROTOCOL, IRMP_ORTEK_PROTOCOL, IRMP_PARAM_FLAG_1ST_PULSE_IS_1, IRMP_PARAM_FLAG_IS_MANCHESTER, IRMP_PARAM_FLAG_IS_SERIAL, IRMP_RC5_PROTOCOL, IRMP_RC6_PROTOCOL, IRMP_RC6A_PROTOCOL, IRMP_RCCAR_PROTOCOL, IRMP_RCII_PROTOCOL, IRMP_RCMM12_PROTOCOL, IRMP_RCMM24_PROTOCOL, IRMP_RCMM32_PROTOCOL, IRMP_ROOMBA_PROTOCOL, IRMP_RUWIDO_PROTOCOL, IRMP_S100_PROTOCOL, IRMP_SAMSUNG32_PROTOCOL, IRMP_SAMSUNG48_PROTOCOL, IRMP_SAMSUNG_PROTOCOL, IRMP_SIEMENS_PROTOCOL, IRMP_SIRCS_PROTOCOL, IRMP_SPEAKER_PROTOCOL, IRMP_SUPPORT_MANCHESTER, IRMP_SUPPORT_SERIAL, IRMP_TECHNICS_PROTOCOL, IRMP_THOMSON_PROTOCOL, IRMP_TIMEOUT_LEN, JVC_REPEAT_START_BIT_PAUSE_LEN_MAX, JVC_REPEAT_START_BIT_PAUSE_LEN_MIN, JVC_START_BIT_PULSE_LEN_MAX, JVC_START_BIT_PULSE_LEN_MIN, JVC_START_BIT_PULSE_TIME, KASEIKYO_START_BIT_PAUSE_LEN_MAX, KASEIKYO_START_BIT_PAUSE_LEN_MIN, KASEIKYO_START_BIT_PULSE_LEN_MAX, KASEIKYO_START_BIT_PULSE_LEN_MIN, KATHREIN_1_PULSE_LEN_MAX, KATHREIN_1_PULSE_LEN_MIN, KATHREIN_START_BIT_PAUSE_LEN_MAX, KATHREIN_START_BIT_PAUSE_LEN_MIN, KATHREIN_START_BIT_PULSE_LEN_MAX, KATHREIN_START_BIT_PULSE_LEN_MIN, KATHREIN_SYNC_BIT_PAUSE_LEN_MAX, KATHREIN_SYNC_BIT_PAUSE_LEN_MIN, LEGO_START_BIT_PAUSE_LEN_MAX, LEGO_START_BIT_PAUSE_LEN_MIN, LEGO_START_BIT_PULSE_LEN_MAX, LEGO_START_BIT_PULSE_LEN_MIN, MATSUSHITA_START_BIT_PAUSE_LEN_MAX, MATSUSHITA_START_BIT_PAUSE_LEN_MIN, MATSUSHITA_START_BIT_PULSE_LEN_MAX, MATSUSHITA_START_BIT_PULSE_LEN_MIN, MERLIN_BIT_PAUSE_LEN_MAX, MERLIN_START_BIT_PAUSE_LEN_MAX, MERLIN_START_BIT_PAUSE_LEN_MIN, MERLIN_START_BIT_PULSE_LEN_MAX, MERLIN_START_BIT_PULSE_LEN_MIN, METZ_START_BIT_PAUSE_LEN_MAX, METZ_START_BIT_PAUSE_LEN_MIN, METZ_START_BIT_PULSE_LEN_MAX, METZ_START_BIT_PULSE_LEN_MIN, MITSU_HEAVY_START_BIT_PAUSE_LEN_MAX, MITSU_HEAVY_START_BIT_PAUSE_LEN_MIN, MITSU_HEAVY_START_BIT_PULSE_LEN_MAX, MITSU_HEAVY_START_BIT_PULSE_LEN_MIN, NEC_0_PAUSE_LEN_MAX, NEC_0_PAUSE_LEN_MIN, NEC_FRAME_REPEAT_PAUSE_LEN_MAX, NEC_REPEAT_START_BIT_PAUSE_LEN_MAX, NEC_REPEAT_START_BIT_PAUSE_LEN_MIN, NEC_START_BIT_PAUSE_LEN_MAX, NEC_START_BIT_PAUSE_LEN_MIN, NEC_START_BIT_PULSE_LEN_MAX, NEC_START_BIT_PULSE_LEN_MIN, NETBOX_COMPLETE_DATA_LEN, NETBOX_PULSE_LEN, NETBOX_START_BIT_PAUSE_LEN_MAX, NETBOX_START_BIT_PAUSE_LEN_MIN, NETBOX_START_BIT_PULSE_LEN_MAX, NETBOX_START_BIT_PULSE_LEN_MIN, NIKON_START_BIT_PAUSE_LEN_MAX, NIKON_START_BIT_PAUSE_LEN_MIN, NIKON_START_BIT_PULSE_LEN_MAX, NIKON_START_BIT_PULSE_LEN_MIN, NOKIA_ADDRESS_LEN, NOKIA_ADDRESS_OFFSET, NOKIA_COMMAND_LEN, NOKIA_COMMAND_OFFSET, NUBERT_START_BIT_PAUSE_LEN_MAX, NUBERT_START_BIT_PAUSE_LEN_MIN, NUBERT_START_BIT_PULSE_LEN_MAX, NUBERT_START_BIT_PULSE_LEN_MIN, ORTEK_START_BIT_PAUSE_LEN_MAX, ORTEK_START_BIT_PAUSE_LEN_MIN, ORTEK_START_BIT_PULSE_LEN_MAX, ORTEK_START_BIT_PULSE_LEN_MIN, PANASONIC_START_BIT_PAUSE_LEN_MAX, PANASONIC_START_BIT_PAUSE_LEN_MIN, PANASONIC_START_BIT_PULSE_LEN_MAX, PANASONIC_START_BIT_PULSE_LEN_MIN, PARITY_CHECK_FAILED, PENTAX_START_BIT_PAUSE_LEN_MAX, PENTAX_START_BIT_PAUSE_LEN_MIN, PENTAX_START_BIT_PULSE_LEN_MAX, PENTAX_START_BIT_PULSE_LEN_MIN, RADIO1_START_BIT_PAUSE_LEN_MAX, RADIO1_START_BIT_PAUSE_LEN_MIN, RADIO1_START_BIT_PULSE_LEN_MAX, RADIO1_START_BIT_PULSE_LEN_MIN, RC5_START_BIT_LEN_MAX, RC5_START_BIT_LEN_MIN, RC6_COMPLETE_DATA_LEN_LONG, RC6_START_BIT_PAUSE_LEN_MAX, RC6_START_BIT_PAUSE_LEN_MIN, RC6_START_BIT_PULSE_LEN_MAX, RC6_START_BIT_PULSE_LEN_MIN, RC6_TOGGLE_BIT_LEN_MAX, RC6_TOGGLE_BIT_LEN_MIN, RCCAR_0_PAUSE_LEN_MAX, RCCAR_0_PAUSE_LEN_MIN, RCCAR_1_PAUSE_LEN_MAX, RCCAR_1_PAUSE_LEN_MIN, RCCAR_PULSE_LEN_MAX, RCCAR_PULSE_LEN_MIN, RCCAR_START_BIT_PAUSE_LEN_MAX, RCCAR_START_BIT_PAUSE_LEN_MIN, RCCAR_START_BIT_PULSE_LEN_MAX, RCCAR_START_BIT_PULSE_LEN_MIN, RCII_BIT_LEN, RCII_START_BIT_PAUSE_LEN_MAX, RCII_START_BIT_PAUSE_LEN_MIN, RCII_START_BIT_PULSE_LEN_MAX, RCII_START_BIT_PULSE_LEN_MIN, RCMM32_BIT_01_PAUSE_LEN_MAX, RCMM32_BIT_01_PAUSE_LEN_MIN, RCMM32_BIT_10_PAUSE_LEN_MAX, RCMM32_BIT_10_PAUSE_LEN_MIN, RCMM32_BIT_11_PAUSE_LEN_MAX, RCMM32_BIT_11_PAUSE_LEN_MIN, RCMM32_START_BIT_PAUSE_LEN_MAX, RCMM32_START_BIT_PAUSE_LEN_MIN, RCMM32_START_BIT_PULSE_LEN_MAX, RCMM32_START_BIT_PULSE_LEN_MIN, RECS80_START_BIT_PAUSE_LEN_MAX, RECS80_START_BIT_PAUSE_LEN_MIN, RECS80_START_BIT_PULSE_LEN_MAX, RECS80_START_BIT_PULSE_LEN_MIN, RECS80EXT_START_BIT_PAUSE_LEN_MAX, RECS80EXT_START_BIT_PAUSE_LEN_MIN, RECS80EXT_START_BIT_PULSE_LEN_MAX, RECS80EXT_START_BIT_PULSE_LEN_MIN, ROOMBA_0_PAUSE_LEN, ROOMBA_0_PULSE_LEN_MAX, ROOMBA_0_PULSE_LEN_MIN, ROOMBA_1_PAUSE_LEN_EXACT, ROOMBA_1_PULSE_LEN_MAX, ROOMBA_1_PULSE_LEN_MIN, ROOMBA_COMPLETE_DATA_LEN, ROOMBA_START_BIT_PAUSE_LEN_MAX, ROOMBA_START_BIT_PAUSE_LEN_MIN, ROOMBA_START_BIT_PULSE_LEN_MAX, ROOMBA_START_BIT_PULSE_LEN_MIN, RUWIDO_COMPLETE_DATA_LEN, S100_START_BIT_LEN_MAX, S100_START_BIT_LEN_MIN, SAMSUNG32_COMMAND_LEN, SAMSUNG32_COMMAND_OFFSET, SAMSUNG32_COMPLETE_DATA_LEN, SAMSUNG48_COMMAND_LEN, SAMSUNG48_COMMAND_OFFSET, SAMSUNG48_COMPLETE_DATA_LEN, SAMSUNG_1_PAUSE_LEN_MAX, SAMSUNG_1_PAUSE_LEN_MIN, SAMSUNG_PULSE_LEN_MAX, SAMSUNG_PULSE_LEN_MIN, SAMSUNG_START_BIT_PAUSE_LEN_MAX, SAMSUNG_START_BIT_PAUSE_LEN_MIN, SAMSUNG_START_BIT_PULSE_LEN_MAX, SAMSUNG_START_BIT_PULSE_LEN_MIN, SAMSUNGAH_START_BIT_PAUSE_LEN_MAX, SAMSUNGAH_START_BIT_PAUSE_LEN_MIN, SAMSUNGAH_START_BIT_PULSE_LEN_MAX, SAMSUNGAH_START_BIT_PULSE_LEN_MIN, SIEMENS_ADDRESS_LEN, SIEMENS_ADDRESS_OFFSET, SIEMENS_COMMAND_LEN, SIEMENS_COMMAND_OFFSET, SIEMENS_OR_RUWIDO_START_BIT_PAUSE_LEN_MAX, SIEMENS_OR_RUWIDO_START_BIT_PAUSE_LEN_MIN, SIEMENS_OR_RUWIDO_START_BIT_PULSE_LEN_MAX, SIEMENS_OR_RUWIDO_START_BIT_PULSE_LEN_MIN, SIRCS_MINIMUM_DATA_LEN, SIRCS_PAUSE_LEN_MAX, SIRCS_START_BIT_PAUSE_LEN_MAX, SIRCS_START_BIT_PAUSE_LEN_MIN, SIRCS_START_BIT_PULSE_LEN_MAX, SIRCS_START_BIT_PULSE_LEN_MIN, SPEAKER_START_BIT_PAUSE_LEN_MAX, SPEAKER_START_BIT_PAUSE_LEN_MIN, SPEAKER_START_BIT_PULSE_LEN_MAX, SPEAKER_START_BIT_PULSE_LEN_MIN, TELEFUNKEN_START_BIT_PAUSE_LEN_MAX, TELEFUNKEN_START_BIT_PAUSE_LEN_MIN, TELEFUNKEN_START_BIT_PULSE_LEN_MAX, TELEFUNKEN_START_BIT_PULSE_LEN_MIN, THOMSON_0_PAUSE_LEN_MAX, THOMSON_0_PAUSE_LEN_MIN, THOMSON_1_PAUSE_LEN_MAX, THOMSON_1_PAUSE_LEN_MIN, THOMSON_PULSE_LEN_MAX, THOMSON_PULSE_LEN_MIN, TRUE, VINCENT_START_BIT_PAUSE_LEN_MAX, VINCENT_START_BIT_PAUSE_LEN_MIN, VINCENT_START_BIT_PULSE_LEN_MAX, VINCENT_START_BIT_PULSE_LEN_MIN.
Referenced by irmp_add_one_sample, irmp_reset_state.
void print_spectrum(char *text, int *buf, int is_pulse)
Referenced by main.
static uint_fast8_t get_fdc_key(uint_fast16_t cmd)
static void next_tick(void)
int main(int argc, char **argv)
References FALSE, print_spectrum, TRUE.