grp_instances
static void oldpins_array_seed(struct otd_decoder_inst *di)
static void oldpins_array_free(struct otd_decoder_inst *di)
OTD_API int otd_inst_option_set(struct otd_decoder_inst *di, GHashTable *options)
Set one or more options in a decoder instance.
Handled options are removed from the hash. di Decoder instance. options A GHashTable of options to set. OTD_OK upon success, a (negative) error code otherwise. 0.1.0
References otd_decoder_inst::decoder, otd_decoder_option::def, otd_decoder_option::id, otd_decoder_inst::inst_id, otd_decoder::options, otd_err, OTD_ERR_ARG, OTD_ERR_PYTHON, OTD_OK, otd_warn, otd_decoder::py_dec, otd_decoder_inst::py_inst.
Referenced by otd_inst_new.
static gint compare_channel_id(const struct otd_channel *pdch, const char *channel_id)
OTD_API int otd_inst_channel_set_all(struct otd_decoder_inst *di, GHashTable *new_channels)
Set all channels in a decoder instance.
This function sets all channels for the specified decoder instance, i.e., it overwrites any channels that were already defined (if any). di Decoder instance. new_channels A GHashTable of channels to set. Key is channel name, value is the channel number. Samples passed to this instance will be arranged in this order. OTD_OK upon success, a (negative) error code otherwise. 0.4.0
References otd_decoder::channels, otd_decoder_inst::dec_channelmap, otd_decoder_inst::dec_num_channels, otd_decoder_inst::decoder, otd_channel::id, otd_decoder_inst::inst_id, otd_decoder::name, otd_decoder::opt_channels, otd_channel::order, otd_dbg, OTD_ERR, otd_err, OTD_ERR_ARG, OTD_OK.
OTD_API struct otd_decoder_inst * otd_inst_new(struct otd_session *sess, const char *decoder_id, GHashTable *options)
Create a new protocol decoder instance.
sess The session holding the protocol decoder instance. Must not be NULL. decoder_id Decoder 'id' field. options GHashtable of options which override the defaults set in the decoder class. May be NULL. Pointer to a newly allocated struct otd_decoder_inst, or NULL in case of failure. 0.3.0
References otd_decoder_inst::abs_cur_samplenum, otd_decoder_inst::abs_end_samplenum, otd_decoder_inst::abs_start_samplenum, otd_decoder_inst::channel_samples, otd_decoder::channels, otd_decoder_inst::communicate_eof, otd_decoder_inst::condition_list, otd_decoder_inst::data_mutex, otd_decoder_inst::dec_channelmap, otd_decoder_inst::dec_num_channels, otd_decoder_inst::decoder, otd_decoder_inst::decoder_state, otd_session::di_list, FALSE, otd_decoder_inst::got_new_samples, otd_decoder_inst::got_new_samples_cond, otd_decoder_inst::handled_all_samples, otd_decoder_inst::handled_all_samples_cond, otd_decoder_inst::inbuf, otd_decoder_inst::inbuflen, otd_decoder_inst::inst_id, otd_decoder_inst::match_array, otd_decoder::opt_channels, otd_dbg, otd_decoder_get_by_id, otd_err, otd_inst_find_by_id, otd_inst_option_set, OTD_OK, otd_decoder::py_dec, otd_decoder_inst::py_inst, otd_decoder_inst::sess, otd_decoder_inst::thread_handle, otd_decoder_inst::want_wait_terminate.
static void otd_inst_join_decode_thread(struct otd_decoder_inst *di)
static void otd_inst_reset_state(struct otd_decoder_inst *di)
OTD_API int otd_inst_stack(struct otd_session *sess, struct otd_decoder_inst *di_bottom, struct otd_decoder_inst *di_top)
Stack a decoder instance on top of another.
sess The session holding the protocol decoder instances. Must not be NULL. di_bottom The instance on top of which di_top will be stacked. di_top The instance to go on top. OTD_OK upon success, a (negative) error code otherwise. 0.3.0
References otd_decoder_inst::decoder, otd_session::di_list, FALSE, otd_decoder::inputs, otd_decoder_inst::inst_id, otd_decoder_inst::next_di, otd_dbg, otd_err, OTD_ERR_ARG, OTD_OK, otd_warn, otd_decoder::outputs, otd_decoder_inst::sess, TRUE.
static struct otd_decoder_inst * otd_inst_find_by_id_stack(const char *inst_id, struct otd_decoder_inst *stack)
Search a decoder instance and its stack for instance ID.
inst_id ID to search for. stack A decoder instance, potentially with stacked instances. The matching instance, or NULL.
OTD_API struct otd_decoder_inst * otd_inst_find_by_id(struct otd_session *sess, const char *inst_id)
Find a decoder instance by its instance ID.
This will recurse to find the instance anywhere in the stack tree of the given session. sess The session holding the protocol decoder instance. Must not be NULL. inst_id The instance ID to be found. Pointer to struct otd_decoder_inst, or NULL if not found. 0.3.0
References otd_session::di_list, otd_decoder_inst::inst_id, otd_decoder_inst::sess.
Referenced by otd_inst_new.
OTD_API int otd_inst_initial_pins_set_all(struct otd_decoder_inst *di, GArray *initial_pins)
Set the list of initial (assumed) pin values.
di Decoder instance to use. Must not be NULL. initial_pins A GArray of uint8_t values. Must not be NULL. 0.5.0
References otd_decoder_inst::dec_num_channels, otd_decoder_inst::old_pins_array, otd_dbg, otd_err, OTD_ERR_ARG, OTD_OK, TRUE.
OTD_PRIV int otd_inst_start(struct otd_decoder_inst *di)
References otd_decoder_inst::inst_id, otd_decoder_inst::next_di, otd_dbg, OTD_ERR_PYTHON, OTD_OK, otd_decoder_inst::py_inst.
__attribute__((always_inline))
Check whether the specified sample matches the specified term.
In the case of OTD_TERM_SKIP, this function can modify term->num_samples_already_skipped. old_sample The value of the previous sample (0/1). sample The value of the current sample (0/1). term The term that should be checked for a match. Must not be NULL. TRUE The current sample matches the specified term. FALSE The current sample doesn't match the specified term, or an invalid term was provided.
OTD_PRIV void match_array_free(struct otd_decoder_inst *di)
References otd_decoder_inst::match_array, TRUE.
OTD_PRIV void condition_list_free(struct otd_decoder_inst *di)
References otd_decoder_inst::condition_list.
static gboolean have_non_null_conds(const struct otd_decoder_inst *di)
static void update_old_pins_array(struct otd_decoder_inst *di, const uint8_t *sample_pos)
static void update_old_pins_array_initial_pins(struct otd_decoder_inst *di)
static gboolean term_matches(const struct otd_decoder_inst *di, struct otd_term *term, const uint8_t *sample_pos)
static gboolean all_terms_match(const struct otd_decoder_inst *di, const GSList *cond, const uint8_t *sample_pos)
static gboolean at_least_one_condition_matched(const struct otd_decoder_inst *di, unsigned int num_conditions)
static gboolean find_match(struct otd_decoder_inst *di)
OTD_PRIV int process_samples_until_condition_match(struct otd_decoder_inst *di, gboolean *found_match)
Process available samples and check if they match the defined conditions.
This function returns if there is an error, or when a match is found, or when all samples have been processed (whether a match was found or not). This function immediately terminates when the decoder's wait() method invocation shall get terminated. di The decoder instance to use. Must not be NULL. found_match Will be set to TRUE if at least one condition matched, FALSE otherwise. Must not be NULL. OTD_OK No errors occured, see found_match for the result. OTD_ERR_ARG Invalid arguments.
References otd_decoder_inst::abs_cur_samplenum, otd_decoder_inst::abs_end_samplenum, FALSE, otd_dbg, OTD_ERR_ARG, OTD_OK, TRUE, otd_decoder_inst::want_wait_terminate.
static gpointer di_thread(gpointer data)
Worker thread (per PD-stack).
data Pointer to the lowest-level PD's device instance. Must not be NULL. NULL if there was an error.
OTD_PRIV int otd_inst_decode(struct otd_decoder_inst *di, uint64_t abs_start_samplenum, uint64_t abs_end_samplenum, const uint8_t *inbuf, uint64_t inbuflen, uint64_t unitsize)
Decode a chunk of samples.
The calls to this function must provide the samples that shall be used by the protocol decoder in the correct order ([...]5, 6, 4, 7, 8[...] is a bug), starting from sample zero (2, 3, 4, 5, 6[...] is a bug), consecutively, with no gaps (0, 1, 2, 4, 5[...] is a bug). The start- and end-sample numbers are absolute sample numbers (relative to the start of the whole capture/file/stream), i.e. they are not relative sample numbers within the chunk specified by 'inbuf' and 'inbuflen'. Correct example (4096 samples total, 4 chunks @ 1024 samples each): otd_inst_decode(di, 0, 1024, inbuf, 1024, 1); otd_inst_decode(di, 1024, 2048, inbuf, 1024, 1); otd_inst_decode(di, 2048, 3072, inbuf, 1024, 1); otd_inst_decode(di, 3072, 4096, inbuf, 1024, 1); The chunk size ('inbuflen') can be arbitrary and can differ between calls. Correct example (4096 samples total, 7 chunks @ various samples each): otd_inst_decode(di, 0, 1024, inbuf, 1024, 1); otd_inst_decode(di, 1024, 1124, inbuf, 100, 1); otd_inst_decode(di, 1124, 1424, inbuf, 300, 1); otd_inst_decode(di, 1424, 1643, inbuf, 219, 1); otd_inst_decode(di, 1643, 2048, inbuf, 405, 1); otd_inst_decode(di, 2048, 3072, inbuf, 1024, 1); otd_inst_decode(di, 3072, 4096, inbuf, 1024, 1); INCORRECT example (4096 samples total, 4 chunks @ 1024 samples each, but the start- and end-samplenumbers are not absolute): otd_inst_decode(di, 0, 1024, inbuf, 1024, 1); otd_inst_decode(di, 0, 1024, inbuf, 1024, 1); otd_inst_decode(di, 0, 1024, inbuf, 1024, 1); otd_inst_decode(di, 0, 1024, inbuf, 1024, 1); di The decoder instance to call. Must not be NULL. abs_start_samplenum The absolute starting sample number for the buffer's sample set, relative to the start of capture. abs_end_samplenum The absolute ending sample number for the buffer's sample set, relative to the start of capture. inbuf The buffer to decode. Must not be NULL. inbuflen Length of the buffer. Must be > 0. unitsize The number of bytes per sample. Must be > 0. OTD_OK upon success, a (negative) error code otherwise.
References otd_decoder_inst::abs_cur_samplenum, otd_decoder_inst::abs_end_samplenum, otd_decoder_inst::abs_start_samplenum, otd_decoder_inst::data_mutex, otd_decoder_inst::data_unitsize, FALSE, otd_decoder_inst::got_new_samples, otd_decoder_inst::got_new_samples_cond, otd_decoder_inst::handled_all_samples, otd_decoder_inst::handled_all_samples_cond, otd_decoder_inst::inbuf, otd_decoder_inst::inbuflen, otd_decoder_inst::inst_id, otd_dbg, OTD_ERR_ARG, OTD_ERR_TERM_REQ, OTD_OK, otd_decoder_inst::thread_handle, TRUE, otd_decoder_inst::want_wait_terminate.
OTD_PRIV int otd_inst_flush(struct otd_decoder_inst *di)
Flush all data that is pending, bottom decoder first up to the top of the stack.
di The decoder instance to call. Must not be NULL. OTD_OK upon success, a (negative) error code otherwise.
References otd_decoder_inst::decoder_state, otd_decoder_inst::inst_id, otd_decoder_inst::next_di, otd_dbg, OTD_ERR_ARG, OTD_OK, otd_decoder_inst::py_inst.
OTD_PRIV int otd_inst_send_eof(struct otd_decoder_inst *di)
Communicate the end of the stream of sample data to a decoder instance.
di The decoder instance to call. Must not be NULL. OTD_OK upon success, a (negative) error code otherwise.
References otd_decoder_inst::communicate_eof, otd_decoder_inst::data_mutex, FALSE, otd_decoder_inst::got_new_samples, otd_decoder_inst::got_new_samples_cond, otd_decoder_inst::handled_all_samples, otd_decoder_inst::handled_all_samples_cond, otd_decoder_inst::inbuf, otd_decoder_inst::inbuflen, otd_decoder_inst::inst_id, otd_decoder_inst::next_di, otd_dbg, OTD_ERR_ARG, OTD_OK, otd_decoder_inst::thread_handle, TRUE, otd_decoder_inst::want_wait_terminate.
OTD_PRIV int otd_inst_terminate_reset(struct otd_decoder_inst *di)
Terminate current decoder work, prepare for re-use on new input data.
Terminates all decoder operations in the specified decoder instance and the instances stacked on top of it. Resets internal state such that the previously constructed stack can process new input data that is not related to previously processed input data. This avoids the expensive and complex re-construction of decoder stacks. Callers are expected to follow up with start, metadata, and decode calls like they would for newly constructed decoder stacks. di The decoder instance to call. Must not be NULL. OTD_OK upon success, a (negative) error code otherwise.
References otd_decoder_inst::decoder_state, otd_decoder_inst::inst_id, otd_decoder_inst::next_di, otd_dbg, OTD_ERR_ARG, OTD_OK, otd_decoder_inst::py_inst.
OTD_PRIV void otd_inst_free(struct otd_decoder_inst *di)
References otd_decoder_inst::channel_samples, otd_decoder_inst::dec_channelmap, otd_pd_output::di, otd_decoder_inst::inst_id, otd_decoder_inst::next_di, otd_dbg, otd_decoder_inst::pd_output, otd_pd_output::proto_id, otd_decoder_inst::py_inst.
OTD_PRIV void otd_inst_free_all(struct otd_session *sess)
References otd_session::di_list.
Referenced by otd_decoder_unload.