irmp.h
IRMPCONFIG_STAGE1_H
IRMPCONFIG_STAGE2_H
IRMP_FLAG_REPETITION
void irmp_init(void)
uint_fast8_t irmp_get_data(IRMP_DATA *)
References IRMP_PACKED_STRUCT::address, ANALYZE_PRINTF, IRMP_PACKED_STRUCT::command, FALSE, IRMP_PACKED_STRUCT::flags, IRMP_APPLE_PROTOCOL, IRMP_BOSE_PROTOCOL, IRMP_IR60_PROTOCOL, IRMP_KATHREIN_PROTOCOL, IRMP_LEGO_PROTOCOL, IRMP_MERLIN_PROTOCOL, IRMP_METZ_PROTOCOL, IRMP_NEC_PROTOCOL, IRMP_NETBOX_PROTOCOL, IRMP_ONKYO_PROTOCOL, IRMP_RC5_PROTOCOL, IRMP_RCCAR_PROTOCOL, IRMP_RUWIDO_PROTOCOL, IRMP_S100_PROTOCOL, IRMP_SAMSUNG48_PROTOCOL, IRMP_SAMSUNG_PROTOCOL, IRMP_SIEMENS_PROTOCOL, IRMP_UNKNOWN_PROTOCOL, IRMP_VINCENT_PROTOCOL, IRMP_PACKED_STRUCT::protocol, TRUE.
Referenced by irmp_get_result_data, irmp_reset_state.
uint_fast8_t irmp_ISR(void)
References A1TVBOX_START_BIT_PAUSE_LEN_MAX, A1TVBOX_START_BIT_PAUSE_LEN_MIN, A1TVBOX_START_BIT_PULSE_LEN_MAX, A1TVBOX_START_BIT_PULSE_LEN_MIN, ACP24_START_BIT_PAUSE_LEN_MAX, ACP24_START_BIT_PAUSE_LEN_MIN, ACP24_START_BIT_PULSE_LEN_MAX, ACP24_START_BIT_PULSE_LEN_MIN, ANALYZE_NEWLINE, ANALYZE_ONLY_NORMAL_PRINTF, ANALYZE_ONLY_NORMAL_PUTCHAR, ANALYZE_PRINTF, ANALYZE_PUTCHAR, AUTO_FRAME_REPETITION_LEN, BANG_OLUFSEN_R_PAUSE_LEN_MAX, BANG_OLUFSEN_R_PAUSE_LEN_MIN, BANG_OLUFSEN_START_BIT1_PAUSE_LEN_MAX, BANG_OLUFSEN_START_BIT1_PAUSE_LEN_MIN, BANG_OLUFSEN_START_BIT1_PULSE_LEN_MAX, BANG_OLUFSEN_START_BIT1_PULSE_LEN_MIN, BANG_OLUFSEN_START_BIT2_PAUSE_LEN_MAX, BANG_OLUFSEN_START_BIT2_PAUSE_LEN_MIN, BANG_OLUFSEN_START_BIT2_PULSE_LEN_MAX, BANG_OLUFSEN_START_BIT2_PULSE_LEN_MIN, BANG_OLUFSEN_START_BIT3_PAUSE_LEN_MAX, BANG_OLUFSEN_START_BIT3_PAUSE_LEN_MIN, BANG_OLUFSEN_START_BIT3_PULSE_LEN_MAX, BANG_OLUFSEN_START_BIT3_PULSE_LEN_MIN, BANG_OLUFSEN_START_BIT4_PAUSE_LEN_MAX, BANG_OLUFSEN_START_BIT4_PAUSE_LEN_MIN, BANG_OLUFSEN_START_BIT4_PULSE_LEN_MAX, BANG_OLUFSEN_START_BIT4_PULSE_LEN_MIN, BOSE_START_BIT_PAUSE_LEN_MAX, BOSE_START_BIT_PAUSE_LEN_MIN, BOSE_START_BIT_PULSE_LEN_MAX, BOSE_START_BIT_PULSE_LEN_MIN, DENON_0_PAUSE_LEN_MAX, DENON_0_PAUSE_LEN_MIN, DENON_1_PAUSE_LEN_MAX, DENON_1_PAUSE_LEN_MIN, DENON_AUTO_REPETITION_PAUSE_LEN, DENON_PULSE_LEN_MAX, DENON_PULSE_LEN_MIN, FALSE, FAN_0_PAUSE_LEN_MIN, FAN_1_PAUSE_LEN_MIN, FAN_1_PULSE_LEN_MIN, FAN_COMPLETE_DATA_LEN, FAN_START_BIT_PAUSE_LEN_MAX, FAN_START_BIT_PAUSE_LEN_MIN, FAN_START_BIT_PULSE_LEN_MAX, FAN_START_BIT_PULSE_LEN_MIN, FDC_0_PAUSE_LEN_MAX, FDC_0_PAUSE_LEN_MIN, FDC_1_PAUSE_LEN_MAX, FDC_1_PAUSE_LEN_MIN, FDC_PULSE_LEN_MAX, FDC_PULSE_LEN_MIN, FDC_START_BIT_PAUSE_LEN_MAX, FDC_START_BIT_PAUSE_LEN_MIN, FDC_START_BIT_PULSE_LEN_MAX, FDC_START_BIT_PULSE_LEN_MIN, GREE_START_BIT_PAUSE_LEN_MAX, GREE_START_BIT_PAUSE_LEN_MIN, GREE_START_BIT_PULSE_LEN_MAX, GREE_START_BIT_PULSE_LEN_MIN, GRUNDIG_COMPLETE_DATA_LEN, GRUNDIG_NOKIA_IR60_PRE_PAUSE_LEN_MAX, GRUNDIG_NOKIA_IR60_PRE_PAUSE_LEN_MIN, GRUNDIG_NOKIA_IR60_START_BIT_LEN_MAX, GRUNDIG_NOKIA_IR60_START_BIT_LEN_MIN, input, IR60_ADDRESS_LEN, IR60_ADDRESS_OFFSET, IR60_COMMAND_LEN, IR60_COMMAND_OFFSET, IR60_COMPLETE_DATA_LEN, IR60_TIMEOUT_LEN, IRMP16_START_BIT_PAUSE_LEN_MAX, IRMP16_START_BIT_PAUSE_LEN_MIN, IRMP16_START_BIT_PULSE_LEN_MAX, IRMP16_START_BIT_PULSE_LEN_MIN, IRMP_BANG_OLUFSEN_PROTOCOL, IRMP_DENON_PROTOCOL, IRMP_FAN_PROTOCOL, IRMP_FDC_PROTOCOL, IRMP_FLAG_REPETITION, IRMP_GRUNDIG_PROTOCOL, IRMP_IR60_PROTOCOL, IRMP_JVC_PROTOCOL, IRMP_KASEIKYO_PROTOCOL, IRMP_KATHREIN_PROTOCOL, IRMP_KEY_REPETITION_LEN, IRMP_LGAIR_PROTOCOL, irmp_log, IRMP_MATSUSHITA_PROTOCOL, IRMP_MERLIN_PROTOCOL, IRMP_MITSU_HEAVY_PROTOCOL, IRMP_NEC42_PROTOCOL, IRMP_NEC_PROTOCOL, IRMP_NETBOX_PROTOCOL, IRMP_NOKIA_PROTOCOL, IRMP_NUBERT_PROTOCOL, IRMP_ORTEK_PROTOCOL, IRMP_PARAM_FLAG_1ST_PULSE_IS_1, IRMP_PARAM_FLAG_IS_MANCHESTER, IRMP_PARAM_FLAG_IS_SERIAL, IRMP_RC5_PROTOCOL, IRMP_RC6_PROTOCOL, IRMP_RC6A_PROTOCOL, IRMP_RCCAR_PROTOCOL, IRMP_RCII_PROTOCOL, IRMP_RCMM12_PROTOCOL, IRMP_RCMM24_PROTOCOL, IRMP_RCMM32_PROTOCOL, IRMP_ROOMBA_PROTOCOL, IRMP_RUWIDO_PROTOCOL, IRMP_S100_PROTOCOL, IRMP_SAMSUNG32_PROTOCOL, IRMP_SAMSUNG48_PROTOCOL, IRMP_SAMSUNG_PROTOCOL, IRMP_SIEMENS_PROTOCOL, IRMP_SIRCS_PROTOCOL, IRMP_SPEAKER_PROTOCOL, IRMP_SUPPORT_MANCHESTER, IRMP_SUPPORT_SERIAL, IRMP_TECHNICS_PROTOCOL, IRMP_THOMSON_PROTOCOL, IRMP_TIMEOUT_LEN, JVC_REPEAT_START_BIT_PAUSE_LEN_MAX, JVC_REPEAT_START_BIT_PAUSE_LEN_MIN, JVC_START_BIT_PULSE_LEN_MAX, JVC_START_BIT_PULSE_LEN_MIN, JVC_START_BIT_PULSE_TIME, KASEIKYO_START_BIT_PAUSE_LEN_MAX, KASEIKYO_START_BIT_PAUSE_LEN_MIN, KASEIKYO_START_BIT_PULSE_LEN_MAX, KASEIKYO_START_BIT_PULSE_LEN_MIN, KATHREIN_1_PULSE_LEN_MAX, KATHREIN_1_PULSE_LEN_MIN, KATHREIN_START_BIT_PAUSE_LEN_MAX, KATHREIN_START_BIT_PAUSE_LEN_MIN, KATHREIN_START_BIT_PULSE_LEN_MAX, KATHREIN_START_BIT_PULSE_LEN_MIN, KATHREIN_SYNC_BIT_PAUSE_LEN_MAX, KATHREIN_SYNC_BIT_PAUSE_LEN_MIN, LEGO_START_BIT_PAUSE_LEN_MAX, LEGO_START_BIT_PAUSE_LEN_MIN, LEGO_START_BIT_PULSE_LEN_MAX, LEGO_START_BIT_PULSE_LEN_MIN, MATSUSHITA_START_BIT_PAUSE_LEN_MAX, MATSUSHITA_START_BIT_PAUSE_LEN_MIN, MATSUSHITA_START_BIT_PULSE_LEN_MAX, MATSUSHITA_START_BIT_PULSE_LEN_MIN, MERLIN_BIT_PAUSE_LEN_MAX, MERLIN_START_BIT_PAUSE_LEN_MAX, MERLIN_START_BIT_PAUSE_LEN_MIN, MERLIN_START_BIT_PULSE_LEN_MAX, MERLIN_START_BIT_PULSE_LEN_MIN, METZ_START_BIT_PAUSE_LEN_MAX, METZ_START_BIT_PAUSE_LEN_MIN, METZ_START_BIT_PULSE_LEN_MAX, METZ_START_BIT_PULSE_LEN_MIN, MITSU_HEAVY_START_BIT_PAUSE_LEN_MAX, MITSU_HEAVY_START_BIT_PAUSE_LEN_MIN, MITSU_HEAVY_START_BIT_PULSE_LEN_MAX, MITSU_HEAVY_START_BIT_PULSE_LEN_MIN, NEC_0_PAUSE_LEN_MAX, NEC_0_PAUSE_LEN_MIN, NEC_FRAME_REPEAT_PAUSE_LEN_MAX, NEC_REPEAT_START_BIT_PAUSE_LEN_MAX, NEC_REPEAT_START_BIT_PAUSE_LEN_MIN, NEC_START_BIT_PAUSE_LEN_MAX, NEC_START_BIT_PAUSE_LEN_MIN, NEC_START_BIT_PULSE_LEN_MAX, NEC_START_BIT_PULSE_LEN_MIN, NETBOX_COMPLETE_DATA_LEN, NETBOX_PULSE_LEN, NETBOX_START_BIT_PAUSE_LEN_MAX, NETBOX_START_BIT_PAUSE_LEN_MIN, NETBOX_START_BIT_PULSE_LEN_MAX, NETBOX_START_BIT_PULSE_LEN_MIN, NIKON_START_BIT_PAUSE_LEN_MAX, NIKON_START_BIT_PAUSE_LEN_MIN, NIKON_START_BIT_PULSE_LEN_MAX, NIKON_START_BIT_PULSE_LEN_MIN, NOKIA_ADDRESS_LEN, NOKIA_ADDRESS_OFFSET, NOKIA_COMMAND_LEN, NOKIA_COMMAND_OFFSET, NUBERT_START_BIT_PAUSE_LEN_MAX, NUBERT_START_BIT_PAUSE_LEN_MIN, NUBERT_START_BIT_PULSE_LEN_MAX, NUBERT_START_BIT_PULSE_LEN_MIN, ORTEK_START_BIT_PAUSE_LEN_MAX, ORTEK_START_BIT_PAUSE_LEN_MIN, ORTEK_START_BIT_PULSE_LEN_MAX, ORTEK_START_BIT_PULSE_LEN_MIN, PANASONIC_START_BIT_PAUSE_LEN_MAX, PANASONIC_START_BIT_PAUSE_LEN_MIN, PANASONIC_START_BIT_PULSE_LEN_MAX, PANASONIC_START_BIT_PULSE_LEN_MIN, PARITY_CHECK_FAILED, PENTAX_START_BIT_PAUSE_LEN_MAX, PENTAX_START_BIT_PAUSE_LEN_MIN, PENTAX_START_BIT_PULSE_LEN_MAX, PENTAX_START_BIT_PULSE_LEN_MIN, RADIO1_START_BIT_PAUSE_LEN_MAX, RADIO1_START_BIT_PAUSE_LEN_MIN, RADIO1_START_BIT_PULSE_LEN_MAX, RADIO1_START_BIT_PULSE_LEN_MIN, RC5_START_BIT_LEN_MAX, RC5_START_BIT_LEN_MIN, RC6_COMPLETE_DATA_LEN_LONG, RC6_START_BIT_PAUSE_LEN_MAX, RC6_START_BIT_PAUSE_LEN_MIN, RC6_START_BIT_PULSE_LEN_MAX, RC6_START_BIT_PULSE_LEN_MIN, RC6_TOGGLE_BIT_LEN_MAX, RC6_TOGGLE_BIT_LEN_MIN, RCCAR_0_PAUSE_LEN_MAX, RCCAR_0_PAUSE_LEN_MIN, RCCAR_1_PAUSE_LEN_MAX, RCCAR_1_PAUSE_LEN_MIN, RCCAR_PULSE_LEN_MAX, RCCAR_PULSE_LEN_MIN, RCCAR_START_BIT_PAUSE_LEN_MAX, RCCAR_START_BIT_PAUSE_LEN_MIN, RCCAR_START_BIT_PULSE_LEN_MAX, RCCAR_START_BIT_PULSE_LEN_MIN, RCII_BIT_LEN, RCII_START_BIT_PAUSE_LEN_MAX, RCII_START_BIT_PAUSE_LEN_MIN, RCII_START_BIT_PULSE_LEN_MAX, RCII_START_BIT_PULSE_LEN_MIN, RCMM32_BIT_01_PAUSE_LEN_MAX, RCMM32_BIT_01_PAUSE_LEN_MIN, RCMM32_BIT_10_PAUSE_LEN_MAX, RCMM32_BIT_10_PAUSE_LEN_MIN, RCMM32_BIT_11_PAUSE_LEN_MAX, RCMM32_BIT_11_PAUSE_LEN_MIN, RCMM32_START_BIT_PAUSE_LEN_MAX, RCMM32_START_BIT_PAUSE_LEN_MIN, RCMM32_START_BIT_PULSE_LEN_MAX, RCMM32_START_BIT_PULSE_LEN_MIN, RECS80_START_BIT_PAUSE_LEN_MAX, RECS80_START_BIT_PAUSE_LEN_MIN, RECS80_START_BIT_PULSE_LEN_MAX, RECS80_START_BIT_PULSE_LEN_MIN, RECS80EXT_START_BIT_PAUSE_LEN_MAX, RECS80EXT_START_BIT_PAUSE_LEN_MIN, RECS80EXT_START_BIT_PULSE_LEN_MAX, RECS80EXT_START_BIT_PULSE_LEN_MIN, ROOMBA_0_PAUSE_LEN, ROOMBA_0_PULSE_LEN_MAX, ROOMBA_0_PULSE_LEN_MIN, ROOMBA_1_PAUSE_LEN_EXACT, ROOMBA_1_PULSE_LEN_MAX, ROOMBA_1_PULSE_LEN_MIN, ROOMBA_COMPLETE_DATA_LEN, ROOMBA_START_BIT_PAUSE_LEN_MAX, ROOMBA_START_BIT_PAUSE_LEN_MIN, ROOMBA_START_BIT_PULSE_LEN_MAX, ROOMBA_START_BIT_PULSE_LEN_MIN, RUWIDO_COMPLETE_DATA_LEN, S100_START_BIT_LEN_MAX, S100_START_BIT_LEN_MIN, SAMSUNG32_COMMAND_LEN, SAMSUNG32_COMMAND_OFFSET, SAMSUNG32_COMPLETE_DATA_LEN, SAMSUNG48_COMMAND_LEN, SAMSUNG48_COMMAND_OFFSET, SAMSUNG48_COMPLETE_DATA_LEN, SAMSUNG_1_PAUSE_LEN_MAX, SAMSUNG_1_PAUSE_LEN_MIN, SAMSUNG_PULSE_LEN_MAX, SAMSUNG_PULSE_LEN_MIN, SAMSUNG_START_BIT_PAUSE_LEN_MAX, SAMSUNG_START_BIT_PAUSE_LEN_MIN, SAMSUNG_START_BIT_PULSE_LEN_MAX, SAMSUNG_START_BIT_PULSE_LEN_MIN, SAMSUNGAH_START_BIT_PAUSE_LEN_MAX, SAMSUNGAH_START_BIT_PAUSE_LEN_MIN, SAMSUNGAH_START_BIT_PULSE_LEN_MAX, SAMSUNGAH_START_BIT_PULSE_LEN_MIN, SIEMENS_ADDRESS_LEN, SIEMENS_ADDRESS_OFFSET, SIEMENS_COMMAND_LEN, SIEMENS_COMMAND_OFFSET, SIEMENS_OR_RUWIDO_START_BIT_PAUSE_LEN_MAX, SIEMENS_OR_RUWIDO_START_BIT_PAUSE_LEN_MIN, SIEMENS_OR_RUWIDO_START_BIT_PULSE_LEN_MAX, SIEMENS_OR_RUWIDO_START_BIT_PULSE_LEN_MIN, SIRCS_MINIMUM_DATA_LEN, SIRCS_PAUSE_LEN_MAX, SIRCS_START_BIT_PAUSE_LEN_MAX, SIRCS_START_BIT_PAUSE_LEN_MIN, SIRCS_START_BIT_PULSE_LEN_MAX, SIRCS_START_BIT_PULSE_LEN_MIN, SPEAKER_START_BIT_PAUSE_LEN_MAX, SPEAKER_START_BIT_PAUSE_LEN_MIN, SPEAKER_START_BIT_PULSE_LEN_MAX, SPEAKER_START_BIT_PULSE_LEN_MIN, TELEFUNKEN_START_BIT_PAUSE_LEN_MAX, TELEFUNKEN_START_BIT_PAUSE_LEN_MIN, TELEFUNKEN_START_BIT_PULSE_LEN_MAX, TELEFUNKEN_START_BIT_PULSE_LEN_MIN, THOMSON_0_PAUSE_LEN_MAX, THOMSON_0_PAUSE_LEN_MIN, THOMSON_1_PAUSE_LEN_MAX, THOMSON_1_PAUSE_LEN_MIN, THOMSON_PULSE_LEN_MAX, THOMSON_PULSE_LEN_MIN, TRUE, VINCENT_START_BIT_PAUSE_LEN_MAX, VINCENT_START_BIT_PAUSE_LEN_MIN, VINCENT_START_BIT_PULSE_LEN_MAX, VINCENT_START_BIT_PULSE_LEN_MIN.
Referenced by irmp_add_one_sample, irmp_reset_state.