libopentracedecode-internal.h
Py_LIMITED_API
ALL_ZERO
otd_spew
otd_dbg
otd_info
otd_warn
otd_err
OTD_PRIV int otd_log(int loglevel, const char *format,...) G_GNUC_PRINTF(2
OTD_PRIV PyObject * otd_Decoder_type_new(void)
Create the opentracedecode.Decoder type.
The new type object.
References ALL_ZERO.
OTD_PRIV const char * output_type_name(unsigned int idx)
Referenced by otd_pd_output_callback_add.
OTD_PRIV PyObject * otd_logic_type_new(void)
PyMODINIT_FUNC PyInit_opentracedecode(void)
Referenced by otd_init.
OTD_PRIV PyObject * py_import_by_name(const char *name)
Import a Python module by name.
This function is implemented in terms of PyImport_Import() rather than PyImport_ImportModule(), so that the import hooks are not bypassed. name The name of the module to load as UTF-8 string. The Python module object, or NULL if an exception occurred. The caller is responsible for evaluating and clearing the Python error state.
References py_import_by_name.
Referenced by otd_decoder_load, py_import_by_name.
OTD_PRIV int py_attr_as_str(PyObject *py_obj, const char *attr, char **outstr)
Get the value of a Python object's attribute, returned as a newly allocated char *.
py_obj The object to probe. attr Name of the attribute to retrieve. outstr ptr to char * storage to be filled in. OTD_OK upon success, a (negative) error code otherwise. The 'outstr' argument points to a g_malloc()ed string upon success.
References otd_dbg, OTD_ERR_PYTHON, py_attr_as_str, py_str_as_str.
Referenced by otd_decoder_load, py_attr_as_str.
OTD_PRIV int py_attr_as_strlist(PyObject *py_obj, const char *attr, GSList **outstrlist)
Get the value of a Python object's attribute, returned as a newly allocated GSList of char *.
py_obj The object to probe. attr Name of the attribute to retrieve. outstrlist ptr to GSList of char * storage to be filled in. OTD_OK upon success, a (negative) error code otherwise. The 'outstrlist' argument points to a GSList of g_malloc()ed strings upon success.
References otd_dbg, OTD_ERR_PYTHON, OTD_OK, py_attr_as_strlist, py_listitem_as_str.
Referenced by otd_decoder_load, py_attr_as_strlist.
OTD_PRIV int py_dictitem_as_str(PyObject *py_obj, const char *key, char **outstr)
Get the value of a Python dictionary item, returned as a newly allocated char *.
py_obj The dictionary to probe. key Key of the item to retrieve. outstr Pointer to char * storage to be filled in. OTD_OK upon success, a (negative) error code otherwise. The 'outstr' argument points to a g_malloc()ed string upon success.
References otd_dbg, OTD_ERR_PYTHON, py_dictitem_as_str, py_str_as_str.
Referenced by py_dictitem_as_str.
OTD_PRIV int py_listitem_as_str(PyObject *py_obj, Py_ssize_t idx, char **outstr)
Get the value of a Python list item, returned as a newly allocated char *.
py_obj The list to probe. idx Index of the list item to retrieve. outstr Pointer to char * storage to be filled in. OTD_OK upon success, a (negative) error code otherwise. The 'outstr' argument points to a g_malloc()ed string upon success.
References otd_dbg, OTD_ERR_PYTHON, py_listitem_as_str, py_str_as_str.
Referenced by py_attr_as_strlist, py_listitem_as_str.
OTD_PRIV int py_pydictitem_as_str(PyObject *py_obj, PyObject *py_key, char **outstr)
Get the value of a Python dictionary item, returned as a newly allocated char *.
py_obj The dictionary to probe. py_key Key of the item to retrieve. outstr Pointer to char * storage to be filled in. OTD_OK upon success, a (negative) error code otherwise. The 'outstr' argument points to a malloc()ed string upon success.
References otd_dbg, OTD_ERR_ARG, OTD_ERR_PYTHON, py_pydictitem_as_str, py_str_as_str.
Referenced by py_pydictitem_as_str.
OTD_PRIV int py_pydictitem_as_long(PyObject *py_obj, PyObject *py_key, int64_t *out)
Get the value of a Python dictionary item, returned as a newly allocated char *.
py_obj The dictionary to probe. py_key Key of the item to retrieve. out TODO. OTD_OK upon success, a (negative) error code otherwise.
References otd_dbg, OTD_ERR_ARG, OTD_ERR_PYTHON, OTD_OK, py_pydictitem_as_long.
Referenced by py_pydictitem_as_long.
OTD_PRIV int py_str_as_str(PyObject *py_str, char **outstr)
Get the value of a Python unicode string object, returned as a newly allocated char *.
py_str The unicode string object. outstr ptr to char * storage to be filled in. OTD_OK upon success, a (negative) error code otherwise. The 'outstr' argument points to a g_malloc()ed string upon success.
References otd_dbg, OTD_ERR_PYTHON, OTD_OK, py_str_as_str.
Referenced by otd_decoder_doc_get, py_attr_as_str, py_dictitem_as_str, py_listitem_as_str, py_pydictitem_as_str, py_str_as_str.
OTD_PRIV int py_strseq_to_char(PyObject *py_strseq, char ***out_strv)
Convert a Python list of unicode strings to a C string vector.
On success, a pointer to a newly allocated NUL-terminated array of allocated C strings is written to out_strv. The caller must g_free() each string and the array itself. py_strseq The sequence object. out_strv Address of string vector to be filled in. OTD_OK upon success, a (negative) error code otherwise.
References otd_err, OTD_ERR_MALLOC, OTD_ERR_PYTHON, OTD_OK, py_strseq_to_char.
Referenced by py_strseq_to_char.
OTD_PRIV GVariant * py_obj_to_variant(PyObject *py_obj)
Convert a Python scalar object to a GLib variant.
Supported variant types are string, int64 and double. py_obj The Python object. Must not be NULL. A floating reference to a new variant, or NULL on failure.
References otd_err, py_obj_to_variant.
Referenced by py_obj_to_variant.
OTD_PRIV void otd_exception_catch(const char *format,...) G_GNUC_PRINTF(1