name: CI
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build pkg-config \
            libglib2.0-dev python3-dev ruby ruby-dev build-essential
          gem install fpm
          meson setup build -Dprefix=/usr
          meson compile -C build
          meson test -C build --print-errorlogs

      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          rm -rf dist
          meson install -C build --destdir dist
          
          VER="${GITHUB_REF_NAME#v}"
          fpm -s dir -t deb -n opentracedecode -v "$VER" \
            --license GPL-3.0-or-later \
            --maintainer "OpenTraceLab" \
            --url "https://github.com/OpenTraceLab/OpenTraceDecode" \
            --description "OpenTraceDecode: protocol decoding core (Python embedded)" \
            -C dist usr/lib usr/include usr/lib/*/pkgconfig
          
          fpm -s dir -t rpm -n opentracedecode -v "$VER" \
            --license GPL-3.0-or-later \
            --maintainer "OpenTraceLab" \
            --url "https://github.com/OpenTraceLab/OpenTraceDecode" \
            --description "OpenTraceDecode: protocol decoding core (Python embedded)" \
            -C dist usr/lib usr/include usr/lib64/pkgconfig || true

      - name: Upload packages
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: "*.deb *.rpm"

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          brew update
          brew install meson ninja pkg-config glib python
          meson setup build -Dprefix=/usr/local
          meson compile -C build
          meson test -C build --print-errorlogs

      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          rm -rf dist pkg
          meson install -C build --destdir dist
          
          mkdir -p pkg/usr/local
          cp -r dist/usr/local/* pkg/usr/local/
          
          VER="${GITHUB_REF_NAME#v}"
          pkgbuild --root pkg --identifier com.opentracelab.opentracedecode \
            --version "$VER" opentracedecode-$VER.pkg

      - name: Upload package
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: macos-package
          path: "*.pkg"

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-python
      - shell: msys2 {0}
        run: |
          meson setup build -Dprefix=/mingw64
          meson compile -C build
          meson test -C build --print-errorlogs

      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        shell: msys2 {0}
        run: |
          rm -rf dist
          meson install -C build --destdir dist
          
          VER="${GITHUB_REF_NAME#v}"
          cd dist/mingw64
          zip -r ../../opentracedecode-$VER-windows.zip .

      - name: Upload package
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: windows-package
          path: "*.zip"
